spring:
  application:
    name: curdie
# 注释的配置请不要提交，这是给本地测试使用的
# 本地不要提交任何配置
#  datasource:
#    druid:
#    username: ${htcf.db.${spring.application.name}.username:${htcf.env}_${spring.application.name}}
#    password: ${htcf.db.${spring.application.name}.password:${htcf.env}_${spring.application.name}}
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

---
# 没有安装MQ,所以将mq相关模块关闭
# 环境不完善时选择

spring:
  cloud:
    bus:
      enabled: false
hlg:
  esb:
    enable: false